version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - src-network
    php:
        image: php:fpm
        volumes:
            - ./src:/src
        networks:
            - src-network
    #composer:
        #image: composer:1.9
        #volumes:
            #- ./src:/src
networks:
    src-network:
        driver: bridge
